
{
  "plugins": [
      "react"
  ],
  "env":{
      "browser": true,
      "node": true
  },
  "parserOptions": {
      "ecmaVersion": 2018,
      "sourceType": "module"
  },
  "rules": {
      "semi": 2,
      "react/display-name": "off",
      "react/no-unescaped-entities": "off"
  },
  "extends": [
      "eslint:recommended",
      "plugin:react/recommended" 
  ],
  "parser": "babel-eslint",
  "settings": {
    "react": {
      "version": "latest"
    }
  }
}